spring:
  datasource:
    url: jdbc:mysql://sanchun.cvn2liswve6f.us-east-2.rds.amazonaws.com:3306/sanchun?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    naming:
      physical-strategy: com.khwan.domain.config.NamginConfig